apiVersion: v2
name: historian
description: A Helm chart for deploying Hurence Historian into Kubernetes
type: application
version: 0.1.1
appVersion: "1.3.9"

dependencies:
  - name: solr
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-solr
    version: 2.0.4
  - name: grafana
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-grafana
    version: 6.1.11