{{- if .Values.compactor.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "historian.compactor-name" . }}
  labels:
    {{- include "historian-helm.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "historian.compactor.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "historian.compactor.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "historian-helm.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}

      containers:
        - name: historian-compactor
          image: hurence/historian-spark:latest
          command: ["bin/historian-compactor.sh", "start", "-c", "/etc/config/compactor-config.yml", "-s", "/opt/spark",]
          volumeMounts:
          - name: config-volume
            mountPath: /etc/config         
      volumes:
        - name: config-volume
          configMap:
            name: {{ .Release.Name }}-configmap

      restartPolicy: Always

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
