apiVersion: v1
kind: Service
metadata:
  name: {{ include "historian.server-name" . }}
  labels:
    {{- include "historian-helm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "historian.server.selectorLabels" . | nindent 4 }}
